FROM golang:1.7-alpine

# Install some pkackages
RUN apk update && apk add make git

RUN mkdir -p /go/src/github.com/talpert/helloaddon
ADD . /go/src/github.com/talpert/helloaddon
WORKDIR /go/src/github.com/talpert/helloaddon

ENV CGO_ENABLED=0
ENV GOOS=linux
